name: ghc-9.10-from-scratch
on:
  push:
    branches:
      - 'ghc-9.10*'
  schedule:
    - cron:  '0 8 * * 6' # once a week. saturdays at 8am
jobs:
  ghc-9-10:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - name: Install build tools (macOS)
        run: brew install automake
        if: matrix.os == 'macos'
      - name: Install stack
        shell: bash
        run: curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Install ghcup (unix)
        shell: bash
        run: |-
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_GHC_VERSION=9.8.2 BOOTSTRAP_HASKELL_CABAL_VERSION=latest BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK_HOOK=1 BOOTSTRAP_HASKELL_ADJUST_BASHRC=N sh
          echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
          echo "$HOME/.ghcup/ghc/9.8.2/bin" >> $GITHUB_PATH
        if: matrix.os == 'ubuntu' || matrix.os ==  'macos'
      - name: Run hlint-from-scratch (unix)
        shell: bash
        run: |-
          GHCLIB_AZURE=1; export GHCLIB_AZURE
          git clone https://github.com/shayne-fletcher/hlint-from-scratch.git
          hlint-from-scratch/hlint-from-scratch.sh --init="$HOME/project"
          hlint-from-scratch/hlint-from-scratch.sh --ghc-flavor="9.10.1" --stack-yaml=stack-exact.yaml --resolver=ghc-9.8.2 --no-checkout
        if: matrix.os == 'ubuntu' || matrix.os == 'macos'
